@ECHO OFF
SETLOCAL
SET DOCKERFILE=%~dp0\Dockerfile
docker build -f %DOCKERFILE% -t template_repo/alpine:1.0 . || GOTO FAILURE
:SUCCESS
ENDLOCAL
EXIT /B 0

:FAILURE
ECHO UNKNOWN ERROR
ENDLOCAL
EXIT /B 1
